{application, ecs,
 [{description, "Erlang cluster service"},
  {vsn, "0.1"},
  {mod, {ecs, []}},
  {modules, [ecs,
             ecs_master,
             ecs_app,
             ecs_config,
             ecs_config_manager,
             ecs_connectivity,
			 ecs_influx,
             ecs_stat,
			 ecs_statistics,
             ecs_statforwarder,
			 ecs_util]},
  {applications, [ssl]}
 ]}.
